#!/bin/bash

# Vérifier si nombre correct d'arguments
if [ $# -lt 2 ] || [ $# -gt 3 ]; then
    echo "Usage: $0 [-i|--interactive|-a|--automatic] image [database_path]"
    exit 1
fi

# Analyse les arguments de command line
mode=""
image_to_compare="$2"
database_path="$3"

while [[ $# -gt 0 ]]; do
    case "$1" in
        -i | --interactive)
            mode="--interactive"
            shift
            ;;
        -a | --automatic)
            mode="--automatic"
            shift
            ;;
        *)
            shift
            ;;
    esac
done


# Initialiser la database-path à "img/" si elle n'est pas fournie
if [ -z "$database_path" ]; then
    database_path="img/"
fi

# Ajouter un "/" à database_path s'il n'y en a pas
if [ ! -z "$database_path" ] && [ "${database_path: -1}" != "/" ]; then
    database_path="$database_path/"
fi

# Vérifier si le chemin de la base de donnée est un fichier
if [ ! -d "$database_path" ]; then
    echo "The specified database path is not a directory." >&2
    exit 2
fi

# Modifier la variable $PATH pour inclure le fichier img-dist
export PATH="$PATH:$(pwd)/img-dist/"

# Exécuter img-search avec le mode, l'image et le chemin indiqués
./img-search "$mode" "$image_to_compare" "$database_path"

